/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as BlindsRouteImport } from './routes/blinds'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CurtainsRouteImport } from './routes/curtains'
import { Route as InteriorDecorRouteImport } from './routes/interior-decor'
import { Route as OurWorkRouteImport } from './routes/our-work'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const BlindsRoute = BlindsRouteImport.update({
  id: '/blinds',
  path: '/blinds',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CurtainsRoute = CurtainsRouteImport.update({
  id: '/curtains',
  path: '/curtains',
  getParentRoute: () => rootRouteImport,
} as any)
const InteriorDecorRoute = InteriorDecorRouteImport.update({
  id: '/interior-decor',
  path: '/interior-decor',
  getParentRoute: () => rootRouteImport,
} as any)
const OurWorkRoute = OurWorkRouteImport.update({
  id: '/our-work',
  path: '/our-work',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blinds': typeof BlindsRoute
  '/contact': typeof ContactRoute
  '/curtains': typeof CurtainsRoute
  '/interior-decor': typeof InteriorDecorRoute
  '/our-work': typeof OurWorkRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blinds': typeof BlindsRoute
  '/contact': typeof ContactRoute
  '/curtains': typeof CurtainsRoute
  '/interior-decor': typeof InteriorDecorRoute
  '/our-work': typeof OurWorkRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blinds': typeof BlindsRoute
  '/contact': typeof ContactRoute
  '/curtains': typeof CurtainsRoute
  '/interior-decor': typeof InteriorDecorRoute
  '/our-work': typeof OurWorkRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/blinds'
    | '/contact'
    | '/curtains'
    | '/interior-decor'
    | '/our-work'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/blinds'
    | '/contact'
    | '/curtains'
    | '/interior-decor'
    | '/our-work'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/blinds'
    | '/contact'
    | '/curtains'
    | '/interior-decor'
    | '/our-work'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BlindsRoute: typeof BlindsRoute
  ContactRoute: typeof ContactRoute
  CurtainsRoute: typeof CurtainsRoute
  InteriorDecorRoute: typeof InteriorDecorRoute
  OurWorkRoute: typeof OurWorkRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blinds': {
      id: '/blinds'
      path: '/blinds'
      fullPath: '/blinds'
      preLoaderRoute: typeof BlindsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/curtains': {
      id: '/curtains'
      path: '/curtains'
      fullPath: '/curtains'
      preLoaderRoute: typeof CurtainsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interior-decor': {
      id: '/interior-decor'
      path: '/interior-decor'
      fullPath: '/interior-decor'
      preLoaderRoute: typeof InteriorDecorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/our-work': {
      id: '/our-work'
      path: '/our-work'
      fullPath: '/our-work'
      preLoaderRoute: typeof OurWorkRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BlindsRoute: BlindsRoute,
  ContactRoute: ContactRoute,
  CurtainsRoute: CurtainsRoute,
  InteriorDecorRoute: InteriorDecorRoute,
  OurWorkRoute: OurWorkRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
